slogo_team16: application.Turtle Class Reference
application.Turtle Class Reference
Public Member Functions
Turtle ()
double getOrientation ()
void setOrientation (double ori)
void turn (double degrees)
void setVisibility (int state)
int getVisibility ()
Point2D getLoc ()
void setLocation (Point2D newLoc)
void move (double distance)
void updateMyImage (Image newImage)
ImageView getTurtleImage ()
void toggleShowHide (int toShow)
Package Attributes
ImageView myImage
Private Attributes
double myOrientation
int isVisible
Point2D myLoc
Detailed Description
Back-end turtle Keeps track of turtle's data Changes to data made through TurtleHandler
Author
Anika
Definition at line 18 of file Turtle.java.
Constructor & Destructor Documentation
application.Turtle.Turtle ()
constructor to initialize turtle
Definition at line 28 of file Turtle.java.
Member Function Documentation
Point2D application.Turtle.getLoc ()
Returns
current location of the turtle
Definition at line 80 of file Turtle.java.
References application.Turtle.myLoc.
Referenced by application.ViewHandler2.calculateOriginalLocation(), application.ViewHandler.changeLocationOfTurtle(), application.ViewHandler2.getTurtleLocation(), application.ViewHandler.getTurtleLocation(), application.ViewHandler.moveTurtle(), and application.ViewHandler.setTurtleLocToViewTurtleLoc().
double application.Turtle.getOrientation ()
Returns
current orientation of turtle
Definition at line 38 of file Turtle.java.
References application.Turtle.myOrientation.
Referenced by application.ViewHandler2.getTurtleOrientation(), and application.ViewHandler.getTurtleOrientation().
ImageView application.Turtle.getTurtleImage ()
Returns
turtle's visible image
Definition at line 118 of file Turtle.java.
References application.Turtle.myImage.
int application.Turtle.getVisibility ()
Returns
if the turtle is showing or hidden
Definition at line 73 of file Turtle.java.
References application.Turtle.isVisible.
Referenced by application.ViewHandler.isVisible(), and application.ViewHandler2.updateTurtleOnView().
void application.Turtle.move (double distance)
updates the turtle's location by calculating horizontal and vertical components of distance based on turtle's orientation
Parameters
distance
Definition at line 99 of file Turtle.java.
Referenced by application.ViewHandler.moveTurtle().
void application.Turtle.setLocation (Point2D newLoc)
sets location of the turtle to input Point2D parameter
Parameters
newLoc
Definition at line 88 of file Turtle.java.
Referenced by application.ViewHandler.changeLocationOfTurtle(), application.ViewHandler2.setTurtleLocAndMove(), application.ViewHandler2.setTurtleLocToViewTurtleLoc(), and application.ViewHandler.setTurtleLocToViewTurtleLoc().
void application.Turtle.setOrientation (double ori)
sets orientation of turtle
Parameters
ori
Definition at line 46 of file Turtle.java.
Referenced by application.ViewHandler2.setTurtleOrientation(), and application.ViewHandler.setTurtleOrientation().
void application.Turtle.setVisibility (int state)
sets visiblity based on input parameter if state == 1, visibility ON if state == 0, visibility OFF
Parameters
state
Definition at line 66 of file Turtle.java.
Referenced by application.ViewHandler2.showTurtle(), and application.ViewHandler.showTurtle().
void application.Turtle.toggleShowHide (int toShow)
changes visibility of turtle's image based on input parameter toShow == 1 -> VISIBLE toShow == 0 -> HIDDEN
Parameters
toShow
Definition at line 130 of file Turtle.java.
void application.Turtle.turn (double degrees)
updates orientation adds number of degrees to current orientation
Parameters
degrees
Definition at line 56 of file Turtle.java.
Referenced by application.ViewHandler2.rotateTurtle(), and application.ViewHandler.rotateTurtle().
void application.Turtle.updateMyImage (Image newImage)
sets turtle image to input file
Parameters
newImage
Definition at line 108 of file Turtle.java.
Member Data Documentation
int application.Turtle.isVisible private
Definition at line 20 of file Turtle.java.
Referenced by application.Turtle.getVisibility().
ImageView application.Turtle.myImage package
Definition at line 22 of file Turtle.java.
Referenced by application.Turtle.getTurtleImage().
Point2D application.Turtle.myLoc private
Definition at line 21 of file Turtle.java.
Referenced by application.Turtle.getLoc().
double application.Turtle.myOrientation private
Definition at line 19 of file Turtle.java.
Referenced by application.Turtle.getOrientation().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/application/Turtle.java