slogo_team16: gui.GUI Class Reference
gui.GUI Class Reference
Public Member Functions
GUI () throws IOException
BorderPane initialize ()
void setParser (BasicParser p)
BackgroundView getBackgroundView ()
LineView getLineView ()
TurtleView getTurtleView ()
Private Member Functions
void initializeButtons ()
void launchTurtleImageChooser ()
void createColorPickerButtons ()
void createNormalButtons ()
void launchTurtleInfo ()
void createLanguageButtons ()
void launchHelpPage ()
void initializeView ()
void initializeCommandsHistory ()
void initializeTextField ()
Private Attributes
ObservableList< String > myCommandsList = FXCollections.observableArrayList()
BorderPane myBorders
LineView myLineView
TurtleView myTurtleView
BackgroundView myBackgroundView
Button[] myButtons
String[] myButtonNames
ResourceBundle myLabels
HBox mainHBox
BasicParser myParser
UserMadeUtilities myUtils = new UserMadeUtilities()
Static Private Attributes
static final int NUM_BUTTONS = 3
static final int HELP_BUTTON = 0
static final int TURTLE_BUTTON = 1
static final int TURTLE_INFO_BUTTON = 2
static final int HBOX_SPACING = 20
static final int VIEW_HEIGHT = 600
static final int VIEW_WIDTH = 900
static final String HELP_PAGE
static final String BUTTON_STYLE
static final Color DEFAULT_PEN_COLOR = Color.BLACK
static final Color DEFAULT_BACKGROUND_COLOR = Color.WHITE
Detailed Description
Creates the GUI
Author
Andrew Sun
Definition at line 25 of file GUI.java.
Constructor & Destructor Documentation
gui.GUI.GUI () throws IOException
Definition at line 61 of file GUI.java.
References gui.GUI.NUM_BUTTONS.
Member Function Documentation
void gui.GUI.createColorPickerButtons () private
Initializes color picker buttons
Definition at line 114 of file GUI.java.
References gui.BackgroundView.setBackgroundColor(), and gui.LineView.setColor().
Referenced by gui.GUI.initializeButtons().
void gui.GUI.createLanguageButtons () private
Creates the language buttons
Definition at line 154 of file GUI.java.
Referenced by gui.GUI.initializeButtons().
void gui.GUI.createNormalButtons () private
Creates normal "on click buttons" that are passed events for what they need to do when clicked
Definition at line 127 of file GUI.java.
References gui.GUI.BUTTON_STYLE, gui.GUI.HELP_BUTTON, gui.GUI.launchHelpPage(), gui.GUI.launchTurtleImageChooser(), gui.GUI.launchTurtleInfo(), gui.GUI.NUM_BUTTONS, gui.GUI.TURTLE_BUTTON, and gui.GUI.TURTLE_INFO_BUTTON.
Referenced by gui.GUI.initializeButtons().
BackgroundView gui.GUI.getBackgroundView ()
Definition at line 218 of file GUI.java.
References gui.GUI.myBackgroundView.
Referenced by application.Main.start().
LineView gui.GUI.getLineView ()
Definition at line 222 of file GUI.java.
References gui.GUI.myLineView.
Referenced by application.Main.start().
TurtleView gui.GUI.getTurtleView ()
Definition at line 226 of file GUI.java.
References gui.GUI.myTurtleView.
Referenced by application.Main.start().
BorderPane gui.GUI.initialize ()
Initializes the GUI and returns a scene to the Main method.
Parameters
s
Returns
myBorders
Definition at line 74 of file GUI.java.
References gui.GUI.initializeButtons(), gui.GUI.initializeCommandsHistory(), gui.GUI.initializeTextField(), gui.GUI.initializeView(), and gui.GUI.myBorders.
Referenced by application.Main.start().
void gui.GUI.initializeButtons () private
Creates the Color Buttons, normal buttons, and language selection buttons
Definition at line 86 of file GUI.java.
References gui.GUI.createColorPickerButtons(), gui.GUI.createLanguageButtons(), and gui.GUI.createNormalButtons().
Referenced by gui.GUI.initialize().
void gui.GUI.initializeCommandsHistory () private
Initializes commands history
Definition at line 186 of file GUI.java.
References commands.UserMadeUtilities.checkUDCommands(), commands.UserMadeUtilities.checkVars(), commands.UserMadeUtilities.getAllVars(), and commands.UserMadeUtilities.getUDCommands().
Referenced by gui.GUI.initialize().
void gui.GUI.initializeTextField () private
Initializes text field for user to enter commands
Definition at line 202 of file GUI.java.
Referenced by gui.GUI.initialize().
void gui.GUI.initializeView () private
Initializes view
Definition at line 173 of file GUI.java.
Referenced by gui.GUI.initialize().
void gui.GUI.launchHelpPage () private
Launches a help page to go to SLogo Help Page
Definition at line 161 of file GUI.java.
References gui.WebPopUp.start().
Referenced by gui.GUI.createNormalButtons().
void gui.GUI.launchTurtleImageChooser () private
Launches turtle image chooser
Author
Andrew and Anika
Definition at line 102 of file GUI.java.
References gui.TurtleImageChooser.start().
Referenced by gui.GUI.createNormalButtons().
void gui.GUI.launchTurtleInfo () private
Displays turtle information
Definition at line 142 of file GUI.java.
References gui.TurtleView.getTurtleInfo().
Referenced by gui.GUI.createNormalButtons().
void gui.GUI.setParser (BasicParser p)
Definition at line 211 of file GUI.java.
Referenced by application.Main.start().
Member Data Documentation
final String gui.GUI.BUTTON_STYLE static private
Initial value:
=
            "-fx-font: 14 georgia; -fx-text-fill: black;  "
            + "-fx-effect: dropshadow( three-pass-box , rgba(0,0,0,0.6) , 5, 0.0 , 0 , 1 ); "
            + "-fx-border-width: 2 2 2 2; -fx-border-color: #006652; -fx-background-color: white;"
Definition at line 39 of file GUI.java.
Referenced by gui.GUI.createNormalButtons().
final Color gui.GUI.DEFAULT_BACKGROUND_COLOR = Color.WHITE static private
Definition at line 45 of file GUI.java.
final Color gui.GUI.DEFAULT_PEN_COLOR = Color.BLACK static private
Definition at line 44 of file GUI.java.
final int gui.GUI.HBOX_SPACING = 20 static private
Definition at line 32 of file GUI.java.
final int gui.GUI.HELP_BUTTON = 0 static private
Definition at line 28 of file GUI.java.
Referenced by gui.GUI.createNormalButtons().
final String gui.GUI.HELP_PAGE static private
Initial value:
=
            "http://www.cs.duke.edu/courses/compsci308/spring15/assign/03_slogo/commands.php"
Definition at line 37 of file GUI.java.
HBox gui.GUI.mainHBox private
Definition at line 56 of file GUI.java.
BackgroundView gui.GUI.myBackgroundView private
Definition at line 52 of file GUI.java.
Referenced by gui.GUI.getBackgroundView().
BorderPane gui.GUI.myBorders private
Definition at line 49 of file GUI.java.
Referenced by gui.GUI.initialize().
String [] gui.GUI.myButtonNames private
Definition at line 54 of file GUI.java.
Button [] gui.GUI.myButtons private
Definition at line 53 of file GUI.java.
ObservableList<String> gui.GUI.myCommandsList = FXCollections.observableArrayList() private
Definition at line 47 of file GUI.java.
ResourceBundle gui.GUI.myLabels private
Definition at line 55 of file GUI.java.
LineView gui.GUI.myLineView private
Definition at line 50 of file GUI.java.
Referenced by gui.GUI.getLineView().
BasicParser gui.GUI.myParser private
Definition at line 57 of file GUI.java.
TurtleView gui.GUI.myTurtleView private
Definition at line 51 of file GUI.java.
Referenced by gui.GUI.getTurtleView().
UserMadeUtilities gui.GUI.myUtils = new UserMadeUtilities() private
Definition at line 58 of file GUI.java.
final int gui.GUI.NUM_BUTTONS = 3 static private
Definition at line 27 of file GUI.java.
Referenced by gui.GUI.createNormalButtons(), and gui.GUI.GUI().
final int gui.GUI.TURTLE_BUTTON = 1 static private
Definition at line 29 of file GUI.java.
Referenced by gui.GUI.createNormalButtons().
final int gui.GUI.TURTLE_INFO_BUTTON = 2 static private
Definition at line 30 of file GUI.java.
Referenced by gui.GUI.createNormalButtons().
final int gui.GUI.VIEW_HEIGHT = 600 static private
Definition at line 34 of file GUI.java.
final int gui.GUI.VIEW_WIDTH = 900 static private
Definition at line 35 of file GUI.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/gui/GUI.java