slogo_team16: application.ViewHandler Class Reference
application.ViewHandler Class Reference
Public Member Functions
ViewHandler (LineView lv, TurtleView tv, BackgroundView bk, PenHandler penHandler)
void moveTurtle (double distance)
void changeLocationOfTurtle (Point2D newLoc)
void rotateTurtle (double deg)
void setTurtleOrientation (double newAngle)
double getTurtleOrientation ()
Point2D getTurtleLocation ()
void showTurtle (int toShow)
int isVisible ()
void clearScreen ()
void updateTurtleOnView ()
void setBackground (double index)
void setInfoParamsOfTurtleAndLine ()
Private Member Functions
void initializeTurtle ()
Point2D getViewTurtleLocation ()
void setTurtleLocToViewTurtleLoc ()
void moveTurtleImageAndDraw (Point2D locOrig, Point2D locNew)
Private Attributes
LineView myLineView
TurtleView myTurtleView
BackgroundView myBackgroundView
Turtle myTurtle
PenHandler myPenHandler
Detailed Description
Feb 22, 2015 NOTE: Turtle Coordinate system
        ^ +y
        |
        |
        |
---------------—> +x
Canvas / View coordinate system
---------------—> +x | | | | | | | v +y
Therefore, to center the turtle based on the middle of the canvas, put turtle at [(turtleCoordX + X_CENTER), (turtleCoordY - Y_CENTER)]
As a result, movement methods are formatted as follows:
public void moveTurtle(int dist) { myTurtle.setLocation(getViewTurtleLocation()); // set View's turtle location to turtle loc Point2D origLoc = myTurtle.getLoc(); // get turtle location myTurtle.move(dist); // move Point2D newLoc = myTurtle.getLoc(); // get new turtle location this.moveTurtleImageAndDraw(origLoc, newLoc); // pass View new location // view calculates new loc. in terms of turtle coordinates myTurtle.setLocation(getViewTurtleLocation()); // set View's updated turtle location to turtle loc
}
Author
anika
Definition at line 59 of file ViewHandler.java.
Constructor & Destructor Documentation
application.ViewHandler.ViewHandler (LineView lv, TurtleView tv, BackgroundView bk, PenHandler penHandler)
Constructor sets fields of View and Turtle based on parameters
Parameters
view
turtle
Definition at line 73 of file ViewHandler.java.
References application.ViewHandler.initializeTurtle().
Member Function Documentation
void application.ViewHandler.changeLocationOfTurtle (Point2D newLoc)
Moves the turtle from current location to the new location Updates fields in Turtle accordingly
Parameters
newLoc
Definition at line 185 of file ViewHandler.java.
References application.Turtle.getLoc(), application.ViewHandler.moveTurtleImageAndDraw(), application.Turtle.setLocation(), application.ViewHandler.setTurtleLocToViewTurtleLoc(), and application.ViewHandler.updateTurtleOnView().
Referenced by commands.viewCommands.turtleCommands.ClearScreen.execute(), and commands.viewCommands.turtleCommands.Move.goToLocation().
void application.ViewHandler.clearScreen ()
clears screen called if user enters command CLEARSCREEN
Definition at line 280 of file ViewHandler.java.
References gui.LineView.clearScreen().
Referenced by commands.viewCommands.turtleCommands.ClearScreen.execute().
Point2D application.ViewHandler.getTurtleLocation ()
Returns
current location of turtle
Definition at line 248 of file ViewHandler.java.
References application.Turtle.getLoc().
Referenced by commands.viewCommands.turtleCommands.GoTowardsLoc.execute(), commands.viewCommands.turtleCommands.ClearScreen.execute(), commands.viewCommands.turtleCommands.Move.goToLocation(), application.ViewHandler.setInfoParamsOfTurtleAndLine(), and application.ViewHandler.updateTurtleOnView().
double application.ViewHandler.getTurtleOrientation ()
Returns
current orientation of turtle
Definition at line 240 of file ViewHandler.java.
References application.Turtle.getOrientation().
Referenced by commands.viewCommands.turtleCommands.SetHeading.execute(), application.ViewHandler.setInfoParamsOfTurtleAndLine(), and application.ViewHandler.updateTurtleOnView().
Point2D application.ViewHandler.getViewTurtleLocation () private
NOTE: Turtle Coordinate system
      ^ +y
      |
      |
      |
---------------—> +x
Canvas / View coordinate system
---------------—> +x | | | | | | | v +y
therefore, for the Canvas below:
            |--a--|
=========================== || | || || | || _._ || | Q || | || | || b ||___________|___________|| _|_
===========================
Point Q in turtle coordinates = [(XCENTER + a), (YCENTER + b)] while, Point Q in view coordinates = [(Width/2 + a), -(Height/2 - b)]
Returns
location of turtle on view in turtle coordinates
Definition at line 142 of file ViewHandler.java.
References gui.View.getNewPoint().
Referenced by application.ViewHandler.setTurtleLocToViewTurtleLoc().
void application.ViewHandler.initializeTurtle () private
initializes turtle with image calls setInfoParamsOfTurtle() to set initial info
Definition at line 86 of file ViewHandler.java.
References gui.TurtleView.initializeTurtle(), and application.ViewHandler.setInfoParamsOfTurtleAndLine().
Referenced by application.ViewHandler.ViewHandler().
int application.ViewHandler.isVisible ()
Returns
whether or not the turtle is visible returns 1 if visible, returns 0 if hidden
Definition at line 269 of file ViewHandler.java.
References application.Turtle.getVisibility().
Referenced by application.ViewHandler.updateTurtleOnView().
void application.ViewHandler.moveTurtle (double distance)
Moves the turtle from current location by the additional distance Updates fields in Turtle accordingly
Parameters
distance
Definition at line 162 of file ViewHandler.java.
References application.Turtle.getLoc(), application.Turtle.move(), application.ViewHandler.moveTurtleImageAndDraw(), application.ViewHandler.setTurtleLocToViewTurtleLoc(), and application.ViewHandler.updateTurtleOnView().
Referenced by commands.viewCommands.turtleCommands.Move.changeLocation().
void application.ViewHandler.moveTurtleImageAndDraw (Point2D locOrig, Point2D locNew) private
Updates turtle image on View canvas; draws line if pen is down Note: This feature is the primary reason that ViewHandler needs access to current Pen info
Parameters
locOrig
locNew
Definition at line 202 of file ViewHandler.java.
References gui.LineView.drawLine(), application.PenHandler.getPenStatus(), and application.ViewHandler.updateTurtleOnView().
Referenced by application.ViewHandler.changeLocationOfTurtle(), and application.ViewHandler.moveTurtle().
void application.ViewHandler.rotateTurtle (double deg)
sets turtle orientation to current orientation + angle turned Calls method to update view's turtle image
Parameters
deg
Definition at line 219 of file ViewHandler.java.
References application.Turtle.turn(), and application.ViewHandler.updateTurtleOnView().
Referenced by commands.viewCommands.turtleCommands.Rotate.changeOrientation().
void application.ViewHandler.setBackground (double index)
Definition at line 309 of file ViewHandler.java.
void application.ViewHandler.setInfoParamsOfTurtleAndLine ()
Contains information of turtle regarding
x location
y location
orientation
pen status Contains information for Pen for line drawing of thickness of stroke/line Used to display status of turtle to user from GUI
Definition at line 326 of file ViewHandler.java.
References application.PenHandler.getPenStatus(), application.ViewHandler.getTurtleLocation(), application.ViewHandler.getTurtleOrientation(), application.PenHandler.setThicknessParameter(), and gui.TurtleView.setTurtleInfo().
Referenced by application.ViewHandler.initializeTurtle(), and application.ViewHandler.updateTurtleOnView().
void application.ViewHandler.setTurtleLocToViewTurtleLoc () private
sets the turtle's location to View's turtle location
Definition at line 151 of file ViewHandler.java.
References application.Turtle.getLoc(), application.ViewHandler.getViewTurtleLocation(), and application.Turtle.setLocation().
Referenced by application.ViewHandler.changeLocationOfTurtle(), and application.ViewHandler.moveTurtle().
void application.ViewHandler.setTurtleOrientation (double newAngle)
sets turtle orientation to new orientation Calls method to update view's turtle image
Parameters
newAngle
Definition at line 231 of file ViewHandler.java.
References application.Turtle.setOrientation(), and application.ViewHandler.updateTurtleOnView().
Referenced by commands.viewCommands.turtleCommands.GoTowardsLoc.execute(), and commands.viewCommands.turtleCommands.SetHeading.execute().
void application.ViewHandler.showTurtle (int toShow)
sets visibility of turtle based on input parameter If toShow == 1, visibility ON If toShow == 0, visibility OFF
Parameters
toShow
Definition at line 259 of file ViewHandler.java.
References application.Turtle.setVisibility(), and application.ViewHandler.updateTurtleOnView().
void application.ViewHandler.updateTurtleOnView ()
called whenever turtle's image, location, or orientation is changed in order to update the appropriate fields in View
Definition at line 290 of file ViewHandler.java.
References application.ViewHandler.getTurtleLocation(), application.ViewHandler.getTurtleOrientation(), application.ViewHandler.isVisible(), gui.TurtleView.rotateAndMoveTurtle(), application.ViewHandler.setInfoParamsOfTurtleAndLine(), and gui.TurtleView.showTurtle().
Referenced by application.ViewHandler.changeLocationOfTurtle(), application.ViewHandler.moveTurtle(), application.ViewHandler.moveTurtleImageAndDraw(), application.ViewHandler.rotateTurtle(), application.ViewHandler.setTurtleOrientation(), and application.ViewHandler.showTurtle().
Member Data Documentation
BackgroundView application.ViewHandler.myBackgroundView private
Definition at line 63 of file ViewHandler.java.
LineView application.ViewHandler.myLineView private
Definition at line 61 of file ViewHandler.java.
PenHandler application.ViewHandler.myPenHandler private
Definition at line 65 of file ViewHandler.java.
Turtle application.ViewHandler.myTurtle private
Definition at line 64 of file ViewHandler.java.
TurtleView application.ViewHandler.myTurtleView private
Definition at line 62 of file ViewHandler.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/application/ViewHandler.java