slogo_team16: configuration.SetParser Class Reference
configuration.SetParser Class Reference
Public Member Functions
SetParser (CommandFactory cf) throws IOException
double parse (String s) throws ParserError, IOException
Static Public Member Functions
static void main (String[] args) throws IOException, ParserError
Private Member Functions
CommandCenter parse (Queue< String > tokens) throws ParserError
Private Attributes
CommandFactory myFactory
Additional Inherited Members
Protected Member Functions inherited from configuration.Parser
Parser () throws IOException
void setCommandFactory (CommandFactory cf)
abstract double parse (String s) throws ParserError, IOException
void initialize () throws IOException
void setLanguage (String path)
void initializeSyntax ()
void initializeSets () throws IOException
Node buildTree (Queue< String > tokens) throws ParserError
Node buildTree (Queue< String > tokens, String localVar, int iterator) throws ParserError
boolean isListEnd (String s)
boolean isListStart (String s)
boolean isVariable (String s)
boolean isConstant (String s)
boolean isCommand (String s)
void skip (Queue< String > qu)
boolean isEnd (Queue< String > qu)
List< Entry< String, Pattern > > getPatterns ()
Package Attributes inherited from configuration.Parser
String constant
String variable
String command
String liststart
String listend
String groupstart
String groupend
Detailed Description
A subclass dedicated only for set command parsing
Author
Yongjiao Yu
Definition at line 20 of file SetParser.java.
Constructor & Destructor Documentation
configuration.SetParser.SetParser (CommandFactory cf) throws IOException
Definition at line 23 of file SetParser.java.
Member Function Documentation
static void configuration.SetParser.main (String[] args) throws IOException, ParserError static
Definition at line 49 of file SetParser.java.
double configuration.SetParser.parse (String s) throws ParserError, IOException
Definition at line 28 of file SetParser.java.
References commands.viewCommands.turtleCommands.Executable.execute(), configuration.Parser.skip(), and configuration.Util.toCommandQueue().
CommandCenter configuration.SetParser.parse (Queue< String > tokens) throws ParserError private
Definition at line 35 of file SetParser.java.
References configuration.Parser.buildTree(), Tree.Node.getValue(), configuration.Parser.isEnd(), and configuration.Parser.isVariable().
Member Data Documentation
CommandFactory configuration.SetParser.myFactory private
Definition at line 21 of file SetParser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/configuration/SetParser.java