slogo_team16: Tree.BinNode Class Reference
Tree.BinNode Class Reference
Public Member Functions
BinNode (String s, Node l, Node r, CommandFactory cf)
double getValue ()
String toString ()
int hasChild ()
Private Attributes
final int numChild = 2
String command
Node left
Node right
CommandFactory myFactory
Detailed Description
Represents a binary node with two children/operator with two parameters node
Author
Yongjiao Yu
Definition at line 13 of file BinNode.java.
Constructor & Destructor Documentation
Tree.BinNode.BinNode (String s, Node l, Node r, CommandFactory cf)
Definition at line 20 of file BinNode.java.
Member Function Documentation
double Tree.BinNode.getValue ()
Implements Tree.Node.
Definition at line 29 of file BinNode.java.
References commands.viewCommands.turtleCommands.Executable.execute(), Tree.Node.getValue(), and application.CommandFactory.makeBasicCommands().
int Tree.BinNode.hasChild ()
Implements Tree.Node.
Definition at line 47 of file BinNode.java.
References Tree.BinNode.numChild.
String Tree.BinNode.toString ()
Definition at line 39 of file BinNode.java.
Member Data Documentation
String Tree.BinNode.command private
Definition at line 15 of file BinNode.java.
Node Tree.BinNode.left private
Definition at line 16 of file BinNode.java.
CommandFactory Tree.BinNode.myFactory private
Definition at line 18 of file BinNode.java.
final int Tree.BinNode.numChild = 2 private
Definition at line 14 of file BinNode.java.
Referenced by Tree.BinNode.hasChild().
Node Tree.BinNode.right private
Definition at line 17 of file BinNode.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/Tree/BinNode.java