slogo_team16: application.ViewHandler2 Class Reference
application.ViewHandler2 Class Reference
Public Member Functions
ViewHandler2 (LineView lineView, TurtleView turtView, BackgroundView bkView, PenHandler penHandler)
void moveTurtle (double distance)
void changeLocationOfTurtle (Point2D newLoc)
void rotateTurtle (double deg)
void setTurtleOrientation (double newAngle)
void showTurtle (int toShow)
void clearScreen ()
Private Member Functions
void initializeTurtle ()
void setTurtleLocToViewTurtleLoc ()
Point2D calculateOriginalLocation ()
void setTurtleLocAndMove (Point2D originalLocation, Point2D newLocation)
void moveTurtleImageAndDraw (Point2D locOrig, Point2D locNew)
double getTurtleOrientation ()
Point2D getTurtleLocation ()
void updateTurtleOnView ()
void setInfoParamsOfTurtleAndLine ()
Private Attributes
LineView myLineView
TurtleView myTurtleView
BackgroundView myBackgroundView
Turtle myTurtle
PenHandler myPenHandler
boolean IS_TURTLE_VISIBLE = true
Static Private Attributes
static String DEFAULT_TURLTLE_IMAGE = "/resources/rsz_turtle.png"
static int PEN_DOWN = 1
static int VISIBLE = 1
Detailed Description
This class contains methods and parameters to update the LineView, TurtleView, or BackgroundView.
If a command is called to move or rotate the turtle, this class updates the location / orientation of the Turtle. If the Turtle set to IS_TURTLE_VISIBLE, this class calls the appropriate method of TurtleView to update the location of the turtle's image on the screen.
If the pen's status is set to PEN_DOWN, this class calls the line drawing method in LineView.
If a command is called to change the background color, this class calls the color changing method in BackgroundView.
Author
Anika
Version
analysis refactoring
Definition at line 28 of file ViewHandler2.java.
Constructor & Destructor Documentation
application.ViewHandler2.ViewHandler2 (LineView lineView, TurtleView turtView, BackgroundView bkView, PenHandler penHandler)
Constructor sets fields of each View and Turtle based on parameters
Parameters
lineView
turtleView
backgroundView
penHandler
Definition at line 48 of file ViewHandler2.java.
References application.ViewHandler2.initializeTurtle().
Member Function Documentation
Point2D application.ViewHandler2.calculateOriginalLocation () private
helper method for moveTurtle and changeLocationOfTurtle
Returns
Turtle's current location in View coordinates
Definition at line 83 of file ViewHandler2.java.
References application.Turtle.getLoc(), and application.ViewHandler2.setTurtleLocToViewTurtleLoc().
Referenced by application.ViewHandler2.changeLocationOfTurtle(), and application.ViewHandler2.moveTurtle().
void application.ViewHandler2.changeLocationOfTurtle (Point2D newLoc)
by movement command Moves the turtle from current location to the new location
Updates fields in Turtle accordingly
Parameters
newLoc
Definition at line 118 of file ViewHandler2.java.
References application.ViewHandler2.calculateOriginalLocation(), and application.ViewHandler2.setTurtleLocAndMove().
void application.ViewHandler2.clearScreen ()
by CLEARSCREEN command clears all lines on the LineView
Definition at line 190 of file ViewHandler2.java.
References gui.LineView.clearScreen().
Point2D application.ViewHandler2.getTurtleLocation () private
Returns
current location of turtle
Definition at line 169 of file ViewHandler2.java.
References application.Turtle.getLoc().
Referenced by application.ViewHandler2.setInfoParamsOfTurtleAndLine(), and application.ViewHandler2.updateTurtleOnView().
double application.ViewHandler2.getTurtleOrientation () private
Returns
current orientation of turtle
Definition at line 162 of file ViewHandler2.java.
References application.Turtle.getOrientation().
Referenced by application.ViewHandler2.moveTurtle(), application.ViewHandler2.setInfoParamsOfTurtleAndLine(), and application.ViewHandler2.updateTurtleOnView().
void application.ViewHandler2.initializeTurtle () private
initializes turtle with image
calls setInfoParamsOfTurtle() to set initial info
Definition at line 60 of file ViewHandler2.java.
References gui.TurtleView.initializeTurtle(), and application.ViewHandler2.setInfoParamsOfTurtleAndLine().
Referenced by application.ViewHandler2.ViewHandler2().
void application.ViewHandler2.moveTurtle (double distance)
by movement commands Moves the turtle from current location by the additional distance
Updates fields in Turtle accordingly
Parameters
distance
Definition at line 106 of file ViewHandler2.java.
References application.ViewHandler2.calculateOriginalLocation(), application.ViewHandler2.getTurtleOrientation(), and application.ViewHandler2.setTurtleLocAndMove().
void application.ViewHandler2.moveTurtleImageAndDraw (Point2D locOrig, Point2D locNew) private
Updates turtle image on View canvas; draws line if pen is down
Note: This feature is the primary reason that ViewHandler needs access to current Pen info
Parameters
locOrig
locNew
Definition at line 130 of file ViewHandler2.java.
References gui.LineView.drawLine(), application.PenHandler.getPenStatus(), application.ViewHandler2.PEN_DOWN, and application.ViewHandler2.updateTurtleOnView().
Referenced by application.ViewHandler2.setTurtleLocAndMove().
void application.ViewHandler2.rotateTurtle (double deg)
by rotation command sets turtle orientation to current orientation + angle turned
Calls method to update view's turtle image
Parameters
deg
Definition at line 143 of file ViewHandler2.java.
References application.Turtle.turn(), and application.ViewHandler2.updateTurtleOnView().
void application.ViewHandler2.setInfoParamsOfTurtleAndLine () private
Contains information of turtle regarding
- x location
- y location
- orientation
- pen status
Contains information for Pen for line drawing of thickness of stroke/line
Used to display status of turtle to user from GUI
Definition at line 221 of file ViewHandler2.java.
References application.PenHandler.getPenStatus(), application.ViewHandler2.getTurtleLocation(), application.ViewHandler2.getTurtleOrientation(), application.PenHandler.setThicknessParameter(), and gui.TurtleView.setTurtleInfo().
Referenced by application.ViewHandler2.initializeTurtle(), and application.ViewHandler2.updateTurtleOnView().
void application.ViewHandler2.setTurtleLocAndMove (Point2D originalLocation, Point2D newLocation) private
helper method to call View's update methods to move turtle image
Parameters
originalLocation
newLocation
Definition at line 93 of file ViewHandler2.java.
References application.ViewHandler2.moveTurtleImageAndDraw(), application.Turtle.setLocation(), application.ViewHandler2.setTurtleLocToViewTurtleLoc(), and application.ViewHandler2.updateTurtleOnView().
Referenced by application.ViewHandler2.changeLocationOfTurtle(), and application.ViewHandler2.moveTurtle().
void application.ViewHandler2.setTurtleLocToViewTurtleLoc () private
sets the turtle's location to View's turtle location due to differences in coordinate systems
View coordinate system origin at top left of Canvas
Turtle coordinate system origin at [Width/2, Height/2]
Definition at line 75 of file ViewHandler2.java.
References gui.View.getNewPoint(), and application.Turtle.setLocation().
Referenced by application.ViewHandler2.calculateOriginalLocation(), and application.ViewHandler2.setTurtleLocAndMove().
void application.ViewHandler2.setTurtleOrientation (double newAngle)
by rotation command sets turtle orientation to new orientation
Calls method to update view's turtle image
Parameters
newAngle
Definition at line 154 of file ViewHandler2.java.
References application.Turtle.setOrientation(), and application.ViewHandler2.updateTurtleOnView().
void application.ViewHandler2.showTurtle (int toShow)
by showTurtle command sets visibility of turtle based on input parameter
If toShow == 1, visibility ON
If toShow == 0, visibility OFF
Parameters
toShow
Definition at line 180 of file ViewHandler2.java.
References application.Turtle.setVisibility(), and application.ViewHandler2.updateTurtleOnView().
void application.ViewHandler2.updateTurtleOnView () private
called whenever turtle's image, location, or orientation is changed in order to update the appropriate fields in View
Definition at line 199 of file ViewHandler2.java.
References application.ViewHandler2.getTurtleLocation(), application.ViewHandler2.getTurtleOrientation(), application.Turtle.getVisibility(), gui.TurtleView.rotateAndMoveTurtle(), application.ViewHandler2.setInfoParamsOfTurtleAndLine(), gui.TurtleView.showTurtle(), and application.ViewHandler2.VISIBLE.
Referenced by application.ViewHandler2.moveTurtleImageAndDraw(), application.ViewHandler2.rotateTurtle(), application.ViewHandler2.setTurtleLocAndMove(), application.ViewHandler2.setTurtleOrientation(), and application.ViewHandler2.showTurtle().
Member Data Documentation
String application.ViewHandler2.DEFAULT_TURLTLE_IMAGE = "/resources/rsz_turtle.png" static private
Definition at line 35 of file ViewHandler2.java.
boolean application.ViewHandler2.IS_TURTLE_VISIBLE = true private
Definition at line 38 of file ViewHandler2.java.
BackgroundView application.ViewHandler2.myBackgroundView private
Definition at line 32 of file ViewHandler2.java.
LineView application.ViewHandler2.myLineView private
Definition at line 30 of file ViewHandler2.java.
PenHandler application.ViewHandler2.myPenHandler private
Definition at line 34 of file ViewHandler2.java.
Turtle application.ViewHandler2.myTurtle private
Definition at line 33 of file ViewHandler2.java.
TurtleView application.ViewHandler2.myTurtleView private
Definition at line 31 of file ViewHandler2.java.
int application.ViewHandler2.PEN_DOWN = 1 static private
Definition at line 36 of file ViewHandler2.java.
Referenced by application.ViewHandler2.moveTurtleImageAndDraw().
int application.ViewHandler2.VISIBLE = 1 static private
Definition at line 37 of file ViewHandler2.java.
Referenced by application.ViewHandler2.updateTurtleOnView().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/application/ViewHandler2.java