slogo_team16: commands.UserMadeUtilities Class Reference
commands.UserMadeUtilities Class Reference
Public Member Functions
UserMadeUtilities ()
void emptyVars ()
ObservableList< String > getAllVars ()
ObservableList< String > getUDCommands ()
void emptyCommands ()
void checkUDCommands ()
void checkVars ()
Static Public Member Functions
static void putInVars (String str, Double d)
static Double getFromVars (String str)
static boolean containsVars (String str)
static void putInCommands (String str, UserDefined c)
static UserDefined getFromCommands (String str)
Private Attributes
ObservableList< String > myVarsList = FXCollections.observableArrayList()
ObservableList< String > myUserDefinedCommandsList = FXCollections.observableArrayList()
Static Private Attributes
static HashMap< String, Double > globalVars = new HashMap<>()
static HashMap< String, UserDefined > UDCommands = new HashMap<>()
Detailed Description
Definition at line 8 of file UserMadeUtilities.java.
Constructor & Destructor Documentation
commands.UserMadeUtilities.UserMadeUtilities ()
Definition at line 18 of file UserMadeUtilities.java.
Member Function Documentation
void commands.UserMadeUtilities.checkUDCommands ()
Definition at line 58 of file UserMadeUtilities.java.
Referenced by gui.UserInputBox.doInput(), and gui.GUI.initializeCommandsHistory().
void commands.UserMadeUtilities.checkVars ()
Definition at line 66 of file UserMadeUtilities.java.
Referenced by gui.UserInputBox.doInput(), and gui.GUI.initializeCommandsHistory().
static boolean commands.UserMadeUtilities.containsVars (String str) static
Definition at line 34 of file UserMadeUtilities.java.
Referenced by configuration.Parser.buildTree().
void commands.UserMadeUtilities.emptyCommands ()
Definition at line 46 of file UserMadeUtilities.java.
void commands.UserMadeUtilities.emptyVars ()
Definition at line 22 of file UserMadeUtilities.java.
ObservableList<String> commands.UserMadeUtilities.getAllVars ()
Definition at line 38 of file UserMadeUtilities.java.
References commands.UserMadeUtilities.myVarsList.
Referenced by gui.GUI.initializeCommandsHistory().
static UserDefined commands.UserMadeUtilities.getFromCommands (String str) static
Definition at line 54 of file UserMadeUtilities.java.
Referenced by commands.viewCommands.turtleCommands.RunUD.execute().
static Double commands.UserMadeUtilities.getFromVars (String str) static
Definition at line 30 of file UserMadeUtilities.java.
Referenced by configuration.Parser.buildTree().
ObservableList<String> commands.UserMadeUtilities.getUDCommands ()
Definition at line 42 of file UserMadeUtilities.java.
References commands.UserMadeUtilities.myUserDefinedCommandsList.
Referenced by gui.GUI.initializeCommandsHistory().
static void commands.UserMadeUtilities.putInCommands (String str, UserDefined c) static
Definition at line 50 of file UserMadeUtilities.java.
Referenced by commands.To.To().
static void commands.UserMadeUtilities.putInVars (String str, Double d) static
Definition at line 26 of file UserMadeUtilities.java.
Referenced by commands.viewCommands.turtleCommands.Set.execute().
Member Data Documentation
HashMap<String, Double> commands.UserMadeUtilities.globalVars = new HashMap<>() static private
Definition at line 11 of file UserMadeUtilities.java.
ObservableList<String> commands.UserMadeUtilities.myUserDefinedCommandsList = FXCollections.observableArrayList() private
Definition at line 15 of file UserMadeUtilities.java.
Referenced by commands.UserMadeUtilities.getUDCommands().
ObservableList<String> commands.UserMadeUtilities.myVarsList = FXCollections.observableArrayList() private
Definition at line 14 of file UserMadeUtilities.java.
Referenced by commands.UserMadeUtilities.getAllVars().
HashMap<String, UserDefined> commands.UserMadeUtilities.UDCommands = new HashMap<>() static private
Definition at line 12 of file UserMadeUtilities.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/commands/UserMadeUtilities.java