slogo_team16: configuration.BasicParser Class Reference
configuration.BasicParser Class Reference
Public Member Functions
BasicParser (CommandFactory cf) throws IOException
double parse (String s) throws ParserError, IOException
double parse (Queue< String > qu) throws ParserError
void setLanguage (String path)
Private Member Functions
void initializeParsers () throws IOException
Private Attributes
HashMap< String, Parser > myParsers
HashSet< String > userdefined
CommandFactory myFactory
Additional Inherited Members
Protected Member Functions inherited from configuration.Parser
Parser () throws IOException
void setCommandFactory (CommandFactory cf)
abstract double parse (String s) throws ParserError, IOException
void initialize () throws IOException
void setLanguage (String path)
void initializeSyntax ()
void initializeSets () throws IOException
Node buildTree (Queue< String > tokens) throws ParserError
Node buildTree (Queue< String > tokens, String localVar, int iterator) throws ParserError
boolean isListEnd (String s)
boolean isListStart (String s)
boolean isVariable (String s)
boolean isConstant (String s)
boolean isCommand (String s)
void skip (Queue< String > qu)
boolean isEnd (Queue< String > qu)
List< Entry< String, Pattern > > getPatterns ()
Package Attributes inherited from configuration.Parser
String constant
String variable
String command
String liststart
String listend
String groupstart
String groupend
Detailed Description
Parses Command of any kind
Author
Yongjiao Yu
Definition at line 17 of file BasicParser.java.
Constructor & Destructor Documentation
configuration.BasicParser.BasicParser (CommandFactory cf) throws IOException
Definition at line 22 of file BasicParser.java.
References configuration.BasicParser.initializeParsers().
Member Function Documentation
void configuration.BasicParser.initializeParsers () throws IOException private
Definition at line 69 of file BasicParser.java.
Referenced by configuration.BasicParser.BasicParser().
double configuration.BasicParser.parse (String s) throws ParserError, IOException
parses command according to command type
Parameters
user input
Returns
return value of the last executed command
Definition at line 32 of file BasicParser.java.
References configuration.Parser.command, commands.viewCommands.turtleCommands.Executable.execute(), configuration.Util.findCommandKey(), application.CommandFactory.makeNoParmsCommands(), and configuration.Util.toCommandQueue().
Referenced by gui.UserInputBox.doInput().
double configuration.BasicParser.parse (Queue< String > qu) throws ParserError
parses basic (nested) commands, allows only one full command/tree
Parameters
input command in string form
Returns
the result of the last executed commands (if nested)
Exceptions
ParserError
Definition at line 56 of file BasicParser.java.
References configuration.Parser.buildTree(), Tree.Node.getValue(), and Tree.Node.hasChild().
void configuration.BasicParser.setLanguage (String path)
Definition at line 79 of file BasicParser.java.
Referenced by gui.LanguageButton.initialize().
Member Data Documentation
CommandFactory configuration.BasicParser.myFactory private
Definition at line 20 of file BasicParser.java.
HashMap<String, Parser> configuration.BasicParser.myParsers private
Definition at line 18 of file BasicParser.java.
HashSet<String> configuration.BasicParser.userdefined private
Definition at line 19 of file BasicParser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/configuration/BasicParser.java