slogo_team16: configuration.Parser Class Reference
configuration.Parser Class Reference abstract
Protected Member Functions
Parser () throws IOException
abstract double parse (String s) throws ParserError, IOException
void initialize () throws IOException
void setLanguage (String path)
void initializeSyntax ()
void initializeSets () throws IOException
Node buildTree (Queue< String > tokens) throws ParserError
Node buildTree (Queue< String > tokens, String localVar, int iterator) throws ParserError
boolean isListEnd (String s)
boolean isListStart (String s)
boolean isVariable (String s)
boolean isConstant (String s)
boolean isCommand (String s)
void skip (Queue< String > qu)
boolean isEnd (Queue< String > qu)
List< Entry< String, Pattern > > getPatterns ()
Package Attributes
String constant
String variable
String command
String liststart
String listend
String groupstart
String groupend
Private Attributes
String comment
List< Entry< String, Pattern > > patterns
HashSet< String > oneParComs
HashSet< String > twoParComs
Detailed Description
super class for input parsing and validation using expression tree
Author
Yongjiao Yu
Definition at line 18 of file Parser.java.
Constructor & Destructor Documentation
configuration.Parser.Parser () throws IOException protected
Definition at line 24 of file Parser.java.
References configuration.Parser.initialize().
Member Function Documentation
Node configuration.Parser.buildTree (Queue< String > tokens) throws ParserError protected
parses commands till a full command is parsed or when a single tree is built.
Parameters
command tokens
Returns
an expression tree for a full (nested) command
Exceptions
ParserError
Definition at line 63 of file Parser.java.
References commands.UserMadeUtilities.containsVars(), configuration.Util.findCommandKey(), commands.UserMadeUtilities.getFromVars(), configuration.Parser.isCommand(), configuration.Parser.isConstant(), and configuration.Parser.isVariable().
Referenced by configuration.Parser.buildTree(), configuration.IfelseParser.evaluateBoolExpr(), configuration.IfParser.evaluateBoolExpr(), configuration.RepeatParser.fetchNumericExpr(), configuration.ForParser.fetchNumericExpr(), configuration.DotimesParser.fetchNumericExpr(), configuration.SetParser.parse(), configuration.BasicParser.parse(), configuration.RepeatParser.parseFor(), configuration.ForParser.parseFor(), configuration.DotimesParser.parseFor(), configuration.IfelseParser.parseListCommands(), and configuration.IfParser.parseListCommands().
Node configuration.Parser.buildTree (Queue< String > tokens, String localVar, int iterator) throws ParserError protected
Definition at line 95 of file Parser.java.
References configuration.Parser.buildTree(), commands.UserMadeUtilities.containsVars(), configuration.Util.findCommandKey(), commands.UserMadeUtilities.getFromVars(), configuration.Parser.isCommand(), configuration.Parser.isConstant(), and configuration.Parser.isVariable().
List<Entry<String, Pattern> > configuration.Parser.getPatterns () protected
Definition at line 150 of file Parser.java.
References configuration.Parser.patterns.
void configuration.Parser.initialize () throws IOException protected
Definition at line 32 of file Parser.java.
References configuration.Parser.initializeSets(), configuration.Parser.initializeSyntax(), and configuration.Util.makePatterns().
Referenced by configuration.Parser.Parser().
void configuration.Parser.initializeSets () throws IOException protected
Definition at line 53 of file Parser.java.
References configuration.Util.makeSet().
Referenced by configuration.Parser.initialize().
void configuration.Parser.initializeSyntax () protected
Definition at line 42 of file Parser.java.
Referenced by configuration.Parser.initialize().
boolean configuration.Parser.isCommand (String s) protected
Definition at line 141 of file Parser.java.
Referenced by configuration.Parser.buildTree().
boolean configuration.Parser.isConstant (String s) protected
Definition at line 138 of file Parser.java.
Referenced by configuration.Parser.buildTree().
boolean configuration.Parser.isEnd (Queue< String > qu) protected
Definition at line 147 of file Parser.java.
Referenced by configuration.IfelseParser.parse(), configuration.RepeatParser.parse(), configuration.DotimesParser.parse(), configuration.ForParser.parse(), configuration.SetParser.parse(), configuration.IfParser.parse(), configuration.DotimesParser.parseCommands(), configuration.RepeatParser.parseCommands(), configuration.ForParser.parseCommands(), configuration.ForParser.parseFor(), configuration.DotimesParser.parseFor(), configuration.IfelseParser.parseListCommands(), and configuration.IfParser.parseListCommands().
boolean configuration.Parser.isListEnd (String s) protected
Definition at line 129 of file Parser.java.
Referenced by configuration.IfelseParser.parse(), configuration.ForParser.parse(), configuration.DotimesParser.parseCommands(), configuration.RepeatParser.parseCommands(), configuration.ForParser.parseCommands(), configuration.DotimesParser.parseDotimesIterator(), configuration.ForParser.parseFor(), configuration.DotimesParser.parseFor(), configuration.IfParser.parseListCommands(), and configuration.IfelseParser.parseListCommands().
boolean configuration.Parser.isListStart (String s) protected
Definition at line 132 of file Parser.java.
Referenced by configuration.ForParser.parse(), configuration.DotimesParser.parseCommands(), configuration.RepeatParser.parseCommands(), configuration.ForParser.parseCommands(), configuration.DotimesParser.parseDotimesIterator(), configuration.IfParser.parseListCommands(), and configuration.IfelseParser.parseListCommands().
boolean configuration.Parser.isVariable (String s) protected
Definition at line 135 of file Parser.java.
Referenced by configuration.Parser.buildTree(), configuration.ForParser.parse(), configuration.SetParser.parse(), and configuration.DotimesParser.parseDotimesIterator().
abstract double configuration.Parser.parse (String s) throws ParserError, IOException abstract protected
abstract function, parses user input to expression tree and execute
Parameters
user input
Returns
return value of last executed command
void configuration.Parser.setLanguage (String path) protected
Definition at line 38 of file Parser.java.
References configuration.Util.makePatterns().
void configuration.Parser.skip (Queue< String > qu) protected
Definition at line 144 of file Parser.java.
Referenced by configuration.IfelseParser.parse(), configuration.RepeatParser.parse(), configuration.IfParser.parse(), configuration.ForParser.parse(), configuration.DotimesParser.parse(), configuration.SetParser.parse(), configuration.DotimesParser.parseCommands(), configuration.RepeatParser.parseCommands(), configuration.ForParser.parseCommands(), configuration.DotimesParser.parseDotimesIterator(), configuration.ForParser.parseFor(), configuration.DotimesParser.parseFor(), configuration.IfelseParser.parseListCommands(), and configuration.IfParser.parseListCommands().
Member Data Documentation
String configuration.Parser.command package
Definition at line 19 of file Parser.java.
Referenced by configuration.BasicParser.parse().
String configuration.Parser.comment private
Definition at line 19 of file Parser.java.
String configuration.Parser.constant package
Definition at line 19 of file Parser.java.
String configuration.Parser.groupend package
Definition at line 19 of file Parser.java.
String configuration.Parser.groupstart package
Definition at line 19 of file Parser.java.
String configuration.Parser.listend package
Definition at line 19 of file Parser.java.
String configuration.Parser.liststart package
Definition at line 19 of file Parser.java.
HashSet<String> configuration.Parser.oneParComs private
Definition at line 21 of file Parser.java.
List<Entry<String, Pattern> > configuration.Parser.patterns private
Definition at line 20 of file Parser.java.
Referenced by configuration.Parser.getPatterns().
HashSet<String> configuration.Parser.twoParComs private
Definition at line 22 of file Parser.java.
String configuration.Parser.variable package
Definition at line 19 of file Parser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/configuration/Parser.java