slogo_team16: application.PenHandler Class Reference
application.PenHandler Class Reference
Public Member Functions
PenHandler (LineView view)
int getPenStatus ()
void setPenStatus (int statusNew)
void setPenColor (Color newColor)
void setPenColor (int index)
void setPaletteColor (int paletteIndex, int redIndex, int greenIndex, int blueIndex)
Color getPenColor ()
int getPenColorIndex ()
void setPenWeight (double pixels)
double getPenWeight ()
void setThicknessParameter ()
Private Attributes
Pen myPen
LineView myLineView
Detailed Description
Class to handle pen data and update view
Author
anika
Definition at line 11 of file PenHandler.java.
Constructor & Destructor Documentation
application.PenHandler.PenHandler (LineView view)
Constructor to initialize Pen and LineView
Parameters
view = LineView
Definition at line 19 of file PenHandler.java.
Member Function Documentation
Color application.PenHandler.getPenColor ()
Returns
Color of pen
Definition at line 82 of file PenHandler.java.
References application.Pen.getColor().
int application.PenHandler.getPenColorIndex ()
called when PENCOLOR command is executed (Sprint 3)
Returns
Definition at line 91 of file PenHandler.java.
References application.Pen.getCurrentColorIndexFromPalette().
int application.PenHandler.getPenStatus ()
Returns
current status of the Pen
Definition at line 29 of file PenHandler.java.
References application.Pen.getStatus().
Referenced by application.ViewHandler2.moveTurtleImageAndDraw(), application.ViewHandler.moveTurtleImageAndDraw(), application.ViewHandler2.setInfoParamsOfTurtleAndLine(), and application.ViewHandler.setInfoParamsOfTurtleAndLine().
double application.PenHandler.getPenWeight ()
Returns
thickness of pen
Definition at line 108 of file PenHandler.java.
References application.Pen.getWeight().
Referenced by application.PenHandler.setThicknessParameter().
void application.PenHandler.setPaletteColor (int paletteIndex, int redIndex, int greenIndex, int blueIndex)
puts in Pen's Palette map Key: Index; Value: Color(r,g,b)
Parameters
paletteIndex
redIndex
greenIndex
blueIndex
Definition at line 72 of file PenHandler.java.
References application.Pen.setPaletteColor().
void application.PenHandler.setPenColor (Color newColor)
sets color of pen based on input color
Parameters
newColor
Definition at line 49 of file PenHandler.java.
References application.Pen.setColor().
Referenced by application.PenHandler.setPenColor().
void application.PenHandler.setPenColor (int index)
sets color of pen based on input integer accesses Palette map to get returned color
Parameters
index
Definition at line 59 of file PenHandler.java.
References application.Pen.getColorFromPalette(), and application.PenHandler.setPenColor().
void application.PenHandler.setPenStatus (int statusNew)
sets status of pen based on input parameter if status == 1, PENDOWN if status == 0, PENUP
Parameters
statusNew
Definition at line 40 of file PenHandler.java.
References application.Pen.setStatus().
void application.PenHandler.setPenWeight (double pixels)
sets thickness of pen to input pixels
Parameters
pixels
Definition at line 100 of file PenHandler.java.
References application.Pen.setWeight().
void application.PenHandler.setThicknessParameter ()
sets thickness parameter in LineView so that line drawing knows parameters of pen to draw appropriately
Definition at line 117 of file PenHandler.java.
References application.PenHandler.getPenWeight(), and gui.LineView.setThickness().
Referenced by application.ViewHandler2.setInfoParamsOfTurtleAndLine(), and application.ViewHandler.setInfoParamsOfTurtleAndLine().
Member Data Documentation
LineView application.PenHandler.myLineView private
Definition at line 13 of file PenHandler.java.
Pen application.PenHandler.myPen private
Definition at line 12 of file PenHandler.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/application/PenHandler.java