slogo_team16: configuration.IfelseParser Class Reference
configuration.IfelseParser Class Reference
Public Member Functions
double parse (String s) throws IOException, ParserError
Protected Member Functions
IfelseParser (CommandFactory cf) throws IOException
double evaluateBoolExpr (Queue< String > qu) throws ParserError
ArrayList< Node > parseListCommands (Queue< String > qu) throws ParserError
boolean isboolean (String s)
Protected Member Functions inherited from configuration.Parser
Parser () throws IOException
void setCommandFactory (CommandFactory cf)
abstract double parse (String s) throws ParserError, IOException
void initialize () throws IOException
void setLanguage (String path)
void initializeSyntax ()
void initializeSets () throws IOException
Node buildTree (Queue< String > tokens) throws ParserError
Node buildTree (Queue< String > tokens, String localVar, int iterator) throws ParserError
boolean isListEnd (String s)
boolean isListStart (String s)
boolean isVariable (String s)
boolean isConstant (String s)
boolean isCommand (String s)
void skip (Queue< String > qu)
boolean isEnd (Queue< String > qu)
List< Entry< String, Pattern > > getPatterns ()
Private Member Functions
double parse (Queue< String > tokens) throws ParserError
Private Attributes
CommandFactory myFactory
Additional Inherited Members
Package Attributes inherited from configuration.Parser
String constant
String variable
String command
String liststart
String listend
String groupstart
String groupend
Detailed Description
subclass for Ifelse command parsing
Author
Yongjiao Yu
Definition at line 18 of file IfelseParser.java.
Constructor & Destructor Documentation
configuration.IfelseParser.IfelseParser (CommandFactory cf) throws IOException protected
Definition at line 20 of file IfelseParser.java.
Member Function Documentation
double configuration.IfelseParser.evaluateBoolExpr (Queue< String > qu) throws ParserError protected
parses and evaluates the boolean expression
Parameters
command queue
Returns
evaluation result
Definition at line 49 of file IfelseParser.java.
References configuration.Parser.buildTree(), Tree.Node.getValue(), and configuration.IfelseParser.isboolean().
Referenced by configuration.IfelseParser.parse(), and configuration.IfParser.parse().
boolean configuration.IfelseParser.isboolean (String s) protected
Definition at line 75 of file IfelseParser.java.
References configuration.Util.findCommandKey().
Referenced by configuration.IfelseParser.evaluateBoolExpr().
double configuration.IfelseParser.parse (String s) throws IOException, ParserError
Definition at line 24 of file IfelseParser.java.
References configuration.Parser.skip(), and configuration.Util.toCommandQueue().
double configuration.IfelseParser.parse (Queue< String > tokens) throws ParserError private
Definition at line 30 of file IfelseParser.java.
References configuration.IfelseParser.evaluateBoolExpr(), configuration.Util.executeAll(), configuration.Parser.isEnd(), configuration.Parser.isListEnd(), configuration.IfelseParser.parseListCommands(), and configuration.Parser.skip().
ArrayList<Node> configuration.IfelseParser.parseListCommands (Queue< String > qu) throws ParserError protected
parses list of nested commands in bracket. [ command1 command2 command3 ]
Parameters
a queue of commands
Returns
list of tree node representing each command
Exceptions
ParserError
Definition at line 60 of file IfelseParser.java.
References configuration.Parser.buildTree(), configuration.Parser.isEnd(), configuration.Parser.isListEnd(), configuration.Parser.isListStart(), and configuration.Parser.skip().
Referenced by configuration.IfelseParser.parse(), and configuration.IfParser.parse().
Member Data Documentation
CommandFactory configuration.IfelseParser.myFactory private
Definition at line 19 of file IfelseParser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/configuration/IfelseParser.java