slogo_team16: application.CommandFactory Class Reference
application.CommandFactory Class Reference
Public Member Functions
CommandFactory ()
void setPenHandler (PenHandler newHandler)
void setViewHandler (ViewHandler newViewHandler)
CommandCenter makeNoParmsCommands (String com)
CommandCenter makeBasicCommands (String com, ArrayList< Object > parList)
CommandCenter makeBasicCommands (String com, String s, ArrayList< Object > parList)
Private Attributes
PenHandler myPenHandler
ViewHandler myViewHandler
Detailed Description
a Command factory that makes commands.
Author
Yongjiao Yu, modified by Anika
Definition at line 15 of file CommandFactory.java.
Constructor & Destructor Documentation
application.CommandFactory.CommandFactory ()
Definition at line 20 of file CommandFactory.java.
Member Function Documentation
CommandCenter application.CommandFactory.makeBasicCommands (String com, ArrayList< Object > parList)
makes commands where parameters are required.
Parameters
command key, arraylist of parameters of type Double or String
parList
Returns
Definition at line 65 of file CommandFactory.java.
Referenced by Tree.SingleNode.getValue(), and Tree.BinNode.getValue().
CommandCenter application.CommandFactory.makeBasicCommands (String com, String s, ArrayList< Object > parList)
Definition at line 102 of file CommandFactory.java.
CommandCenter application.CommandFactory.makeNoParmsCommands (String com)
Make commands where no paramters are required
Returns
the desired command object
Definition at line 40 of file CommandFactory.java.
Referenced by configuration.BasicParser.parse().
void application.CommandFactory.setPenHandler (PenHandler newHandler)
Definition at line 26 of file CommandFactory.java.
Referenced by application.Main.start().
void application.CommandFactory.setViewHandler (ViewHandler newViewHandler)
Definition at line 31 of file CommandFactory.java.
Referenced by application.Main.start().
Member Data Documentation
PenHandler application.CommandFactory.myPenHandler private
Definition at line 17 of file CommandFactory.java.
ViewHandler application.CommandFactory.myViewHandler private
Definition at line 18 of file CommandFactory.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/application/CommandFactory.java