slogo_team16: gui.View Class Reference
gui.View Class Reference abstract
Public Member Functions
View (int x, int y)
Point2D getNewPoint ()
void setNewPoint (Point2D dest)
double getXOffset ()
double getYOffset ()
Static Package Attributes
static double YOFFSET
Static Private Attributes
static double XOFFSET
static final Point2D DEFAULT_POINT = new Point2D(0,0)
static Point2D newDest
Detailed Description
Creates the view where the lines are drawn and the turtle is displayed.
Author
Andrew Sun
Definition at line 13 of file View.java.
Constructor & Destructor Documentation
gui.View.View (int x, int y)
Definition at line 19 of file View.java.
References gui.View.DEFAULT_POINT.
Member Function Documentation
Point2D gui.View.getNewPoint ()
Returns new point that of the turtle location
Returns
Definition at line 31 of file View.java.
References gui.View.newDest.
Referenced by application.ViewHandler.getViewTurtleLocation(), gui.LineView.LineView(), application.ViewHandler2.setTurtleLocToViewTurtleLoc(), and gui.TurtleView.TurtleView().
double gui.View.getXOffset ()
Definition at line 39 of file View.java.
References gui.View.XOFFSET.
Referenced by gui.TurtleView.TurtleView().
double gui.View.getYOffset ()
Definition at line 43 of file View.java.
References gui.View.YOFFSET.
Referenced by gui.TurtleView.TurtleView().
void gui.View.setNewPoint (Point2D dest)
Definition at line 35 of file View.java.
Referenced by gui.LineView.drawLine(), gui.LineView.findXEdge(), gui.LineView.findYEdge(), and gui.TurtleView.rotateAndMoveTurtle().
Member Data Documentation
final Point2D gui.View.DEFAULT_POINT = new Point2D(0,0) static private
Definition at line 16 of file View.java.
Referenced by gui.View.View().
Point2D gui.View.newDest static private
Definition at line 17 of file View.java.
Referenced by gui.View.getNewPoint().
double gui.View.XOFFSET static private
Definition at line 15 of file View.java.
Referenced by gui.View.getXOffset().
double gui.View.YOFFSET static package
Definition at line 15 of file View.java.
Referenced by gui.View.getYOffset().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/gui/View.java