slogo_team16: configuration.RepeatParser Class Reference
configuration.RepeatParser Class Reference
Public Member Functions
RepeatParser (CommandFactory cf) throws IOException
double parse (String s) throws IOException, ParserError
Static Public Member Functions
static void main (String[] args) throws IOException, ParserError
Private Member Functions
double parse (Queue< String > tokens) throws ParserError
int fetchNumericExpr (Queue< String > qu) throws ParserError
double parseCommands (Queue< String > qu, int iter) throws ParserError
double parseFor (int start, int end, int inc, Queue< String > qu) throws ParserError
Private Attributes
CommandFactory myFactory
Additional Inherited Members
Protected Member Functions inherited from configuration.Parser
Parser () throws IOException
void setCommandFactory (CommandFactory cf)
abstract double parse (String s) throws ParserError, IOException
void initialize () throws IOException
void setLanguage (String path)
void initializeSyntax ()
void initializeSets () throws IOException
Node buildTree (Queue< String > tokens) throws ParserError
Node buildTree (Queue< String > tokens, String localVar, int iterator) throws ParserError
boolean isListEnd (String s)
boolean isListStart (String s)
boolean isVariable (String s)
boolean isConstant (String s)
boolean isCommand (String s)
void skip (Queue< String > qu)
boolean isEnd (Queue< String > qu)
List< Entry< String, Pattern > > getPatterns ()
Package Attributes inherited from configuration.Parser
String constant
String variable
String command
String liststart
String listend
String groupstart
String groupend
Detailed Description
subclass for Repeat command parsing
Author
Yongjiao Yu
Definition at line 17 of file RepeatParser.java.
Constructor & Destructor Documentation
configuration.RepeatParser.RepeatParser (CommandFactory cf) throws IOException
Definition at line 20 of file RepeatParser.java.
Member Function Documentation
int configuration.RepeatParser.fetchNumericExpr (Queue< String > qu) throws ParserError private
Definition at line 40 of file RepeatParser.java.
References configuration.Parser.buildTree(), and Tree.Node.getValue().
Referenced by configuration.RepeatParser.parse().
static void configuration.RepeatParser.main (String[] args) throws IOException, ParserError static
Definition at line 72 of file RepeatParser.java.
double configuration.RepeatParser.parse (String s) throws IOException, ParserError
Definition at line 25 of file RepeatParser.java.
References configuration.Parser.skip(), and configuration.Util.toCommandQueue().
double configuration.RepeatParser.parse (Queue< String > tokens) throws ParserError private
Definition at line 31 of file RepeatParser.java.
References configuration.RepeatParser.fetchNumericExpr(), configuration.Parser.isEnd(), and configuration.RepeatParser.parseCommands().
double configuration.RepeatParser.parseCommands (Queue< String > qu, int iter) throws ParserError private
Definition at line 48 of file RepeatParser.java.
References configuration.Parser.isEnd(), configuration.Parser.isListEnd(), configuration.Parser.isListStart(), configuration.RepeatParser.parseFor(), and configuration.Parser.skip().
Referenced by configuration.RepeatParser.parse().
double configuration.RepeatParser.parseFor (int start, int end, int inc, Queue< String > qu) throws ParserError private
Definition at line 60 of file RepeatParser.java.
References configuration.Parser.buildTree(), and Tree.Node.getValue().
Referenced by configuration.RepeatParser.parseCommands().
Member Data Documentation
CommandFactory configuration.RepeatParser.myFactory private
Definition at line 18 of file RepeatParser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/configuration/RepeatParser.java