slogo_team16: commands.UserDefined Class Reference
commands.UserDefined Class Reference
Public Member Functions
UserDefined (String name, ArrayList< String > p, ArrayList< CommandCenter > commands)
UserDefined makeInstanceOfSelf ()
void setName (String n)
String getName ()
void setParameters (ArrayList< String > p)
ArrayList< String > getParameters ()
void setCommands (ArrayList< CommandCenter > c)
ArrayList< CommandCenter > getCommands ()
double execute ()
Public Member Functions inherited from commands.CommandCenter
CommandCenter ()
void restore (ArrayList< Integer > l, String s)
Protected Attributes
ArrayList< String > params
Private Attributes
String myName
ArrayList< CommandCenter > comms
Additional Inherited Members
Protected Member Functions inherited from commands.CommandCenter
void setParams (ArrayList< Object > newParams)
ArrayList< Object > getParams ()
Detailed Description
Definition at line 5 of file UserDefined.java.
Constructor & Destructor Documentation
commands.UserDefined.UserDefined (String name, ArrayList< String > p, ArrayList< CommandCenter > commands)
Definition at line 11 of file UserDefined.java.
Referenced by commands.UserDefined.makeInstanceOfSelf().
Member Function Documentation
double commands.UserDefined.execute ()
Implements commands.viewCommands.turtleCommands.Executable.
Definition at line 47 of file UserDefined.java.
ArrayList<CommandCenter> commands.UserDefined.getCommands ()
Definition at line 42 of file UserDefined.java.
References commands.UserDefined.comms.
Referenced by commands.viewCommands.turtleCommands.RunUD.execute().
String commands.UserDefined.getName ()
Definition at line 26 of file UserDefined.java.
References commands.UserDefined.myName.
ArrayList<String> commands.UserDefined.getParameters ()
Definition at line 34 of file UserDefined.java.
References commands.UserDefined.params.
Referenced by commands.viewCommands.turtleCommands.RunUD.execute().
UserDefined commands.UserDefined.makeInstanceOfSelf ()
Definition at line 17 of file UserDefined.java.
References commands.UserDefined.UserDefined().
Referenced by commands.viewCommands.turtleCommands.RunUD.execute().
void commands.UserDefined.setCommands (ArrayList< CommandCenter > c)
Definition at line 38 of file UserDefined.java.
void commands.UserDefined.setName (String n)
Definition at line 22 of file UserDefined.java.
void commands.UserDefined.setParameters (ArrayList< String > p)
Definition at line 30 of file UserDefined.java.
Member Data Documentation
ArrayList<CommandCenter> commands.UserDefined.comms private
Definition at line 9 of file UserDefined.java.
Referenced by commands.UserDefined.getCommands().
String commands.UserDefined.myName private
Definition at line 7 of file UserDefined.java.
Referenced by commands.UserDefined.getName().
ArrayList<String> commands.UserDefined.params protected
Definition at line 8 of file UserDefined.java.
Referenced by commands.UserDefined.getParameters().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/commands/UserDefined.java