slogo_team16: commands.viewCommands.turtleCommands.Executable Interface Reference
commands.viewCommands.turtleCommands.Executable Interface Reference
Public Member Functions
double execute ()
Detailed Description
Each command is executable
Author
anika
Definition at line 8 of file Executable.java.
Member Function Documentation
double commands.viewCommands.turtleCommands.Executable.execute ()
Implemented in commands.UserDefined, commands.viewCommands.turtleCommands.TurtleCommands, commands.viewCommands.ViewCommands, commands.arithmeticCommands.Add, commands.viewCommands.turtleCommands.RunUD, commands.viewCommands.SetPalette, commands.viewCommands.SetPenColor, commands.viewCommands.turtleCommands.Set, commands.MultTurts, commands.viewCommands.SetPenSize, commands.arithmeticCommands.Random, commands.viewCommands.turtleCommands.ClearScreen, commands.viewCommands.turtleCommands.GoToLocation, commands.arithmeticCommands.Minus, commands.arithmeticCommands.Pow, commands.To, commands.viewCommands.PenColor, commands.viewCommands.turtleCommands.Backward, commands.viewCommands.turtleCommands.Forward, commands.viewCommands.turtleCommands.GoTowardsLoc, commands.viewCommands.turtleCommands.Left, commands.viewCommands.turtleCommands.Right, commands.viewCommands.turtleCommands.SetBackground, commands.viewCommands.turtleCommands.SetHeading, commands.arithmeticCommands.ATan, commands.arithmeticCommands.Cos, commands.arithmeticCommands.Divide, commands.arithmeticCommands.Equal, commands.arithmeticCommands.Greater, commands.arithmeticCommands.Less, commands.arithmeticCommands.Log, commands.arithmeticCommands.Multiply, commands.arithmeticCommands.Not, commands.arithmeticCommands.NotEq, commands.arithmeticCommands.Or, commands.arithmeticCommands.Remainder, commands.arithmeticCommands.Sin, commands.arithmeticCommands.Subtract, commands.arithmeticCommands.Tan, commands.viewCommands.IsPD, commands.viewCommands.PenDown, commands.viewCommands.PenUp, commands.arithmeticCommands.And, commands.viewCommands.turtleCommands.Heading, commands.viewCommands.turtleCommands.HideTurtle, commands.viewCommands.turtleCommands.Home, commands.viewCommands.turtleCommands.Showing, commands.viewCommands.turtleCommands.ShowTurtle, commands.viewCommands.turtleCommands.XCor, commands.viewCommands.turtleCommands.YCor, and commands.arithmeticCommands.PI.
Referenced by Tree.SingleNode.getValue(), Tree.BinNode.getValue(), configuration.SetParser.parse(), and configuration.BasicParser.parse().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/commands/viewCommands/turtleCommands/Executable.java