slogo_team16: gui.TurtleView Class Reference
gui.TurtleView Class Reference
Public Member Functions
TurtleView (int x, int y)
void initializeTurtle (Image turtle)
void rotateAndMoveTurtle (Point2D newLoc, double angle)
void showTurtle (boolean b)
void updateTurtleImage (File loc)
void updateTurtleImage (Image image)
void setTurtleInfo (String info)
String getTurtleInfo ()
Public Member Functions inherited from gui.View
View (int x, int y)
Point2D getNewPoint ()
void setNewPoint (Point2D dest)
double getXOffset ()
double getYOffset ()
Package Attributes
double YOFFSET
Private Member Functions
void rotate (double angle, double x, double y)
Private Attributes
ImageView myTurtle
double currentRotation
double XOFFSET
GraphicsContext turtleGC
Point2D newDest
String myTurtleInfo
Additional Inherited Members
Static Package Attributes inherited from gui.View
static double YOFFSET
Detailed Description
Creates the layer that displays the turtle
Author
Andrew
Definition at line 16 of file TurtleView.java.
Constructor & Destructor Documentation
gui.TurtleView.TurtleView (int x, int y)
Definition at line 25 of file TurtleView.java.
References gui.View.getNewPoint(), gui.View.getXOffset(), and gui.View.getYOffset().
Member Function Documentation
String gui.TurtleView.getTurtleInfo ()
Author
Anika
Returns
Definition at line 114 of file TurtleView.java.
References gui.TurtleView.myTurtleInfo.
Referenced by gui.GUI.launchTurtleInfo().
void gui.TurtleView.initializeTurtle (Image turtle)
Definition at line 35 of file TurtleView.java.
Referenced by application.ViewHandler.initializeTurtle().
void gui.TurtleView.rotate (double angle, double x, double y) private
Rotates the turtle
Parameters
angle
x
y
Definition at line 93 of file TurtleView.java.
Referenced by gui.TurtleView.rotateAndMoveTurtle(), and gui.TurtleView.updateTurtleImage().
void gui.TurtleView.rotateAndMoveTurtle (Point2D newLoc, double angle)
changes location and/or orientation of turtle image
Parameters
newLoc
turtleImage
Definition at line 47 of file TurtleView.java.
References gui.TurtleView.rotate(), gui.View.setNewPoint(), gui.TurtleView.XOFFSET, and gui.TurtleView.YOFFSET.
Referenced by application.ViewHandler.updateTurtleOnView().
void gui.TurtleView.setTurtleInfo (String info)
Author
Anika
Parameters
info
Definition at line 105 of file TurtleView.java.
Referenced by application.ViewHandler.setInfoParamsOfTurtleAndLine().
void gui.TurtleView.showTurtle (boolean b)
Sets turtle visibility
Parameters
b
Definition at line 64 of file TurtleView.java.
Referenced by application.ViewHandler.updateTurtleOnView().
void gui.TurtleView.updateTurtleImage (File loc)
Updates the turtle image either by file or location
Parameters
loc
Definition at line 72 of file TurtleView.java.
Referenced by gui.TurtleImageChooser.chooseTurtleImage(), and gui.TurtleImageChooser.initialize().
void gui.TurtleView.updateTurtleImage (Image image)
Definition at line 77 of file TurtleView.java.
References gui.TurtleView.rotate(), gui.TurtleView.XOFFSET, and gui.TurtleView.YOFFSET.
Member Data Documentation
double gui.TurtleView.currentRotation private
Definition at line 19 of file TurtleView.java.
ImageView gui.TurtleView.myTurtle private
Definition at line 18 of file TurtleView.java.
String gui.TurtleView.myTurtleInfo private
Definition at line 23 of file TurtleView.java.
Referenced by gui.TurtleView.getTurtleInfo().
Point2D gui.TurtleView.newDest private
Definition at line 22 of file TurtleView.java.
GraphicsContext gui.TurtleView.turtleGC private
Definition at line 21 of file TurtleView.java.
double gui.TurtleView.XOFFSET private
Definition at line 20 of file TurtleView.java.
Referenced by gui.TurtleView.rotateAndMoveTurtle(), and gui.TurtleView.updateTurtleImage().
double gui.TurtleView.YOFFSET package
Definition at line 20 of file TurtleView.java.
Referenced by gui.TurtleView.rotateAndMoveTurtle(), and gui.TurtleView.updateTurtleImage().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/gui/TurtleView.java