slogo_team16: gui.UserInputBox Class Reference
gui.UserInputBox Class Reference
Public Member Functions
UserInputBox (BasicParser p, ObservableList< String > list, UserMadeUtilities myUtils, TextField errorBox)
void setParser (BasicParser p)
Private Member Functions
void doInput (KeyEvent e, ObservableList< String > list, UserMadeUtilities myUtils, TextField errorBox)
Private Attributes
BasicParser myParser
Detailed Description
Creates the textfield for the user to input information
Author
Andrew
Definition at line 22 of file UserInputBox.java.
Constructor & Destructor Documentation
gui.UserInputBox.UserInputBox (BasicParser p, ObservableList< String > list, UserMadeUtilities myUtils, TextField errorBox)
Definition at line 26 of file UserInputBox.java.
References gui.UserInputBox.doInput().
Member Function Documentation
void gui.UserInputBox.doInput (KeyEvent e, ObservableList< String > list, UserMadeUtilities myUtils, TextField errorBox) private
Sends information to parser/errorcheck
Parameters
e
p
list
myUtils
errorBox
Definition at line 40 of file UserInputBox.java.
References commands.UserMadeUtilities.checkUDCommands(), commands.UserMadeUtilities.checkVars(), and configuration.BasicParser.parse().
Referenced by gui.UserInputBox.UserInputBox().
void gui.UserInputBox.setParser (BasicParser p)
Definition at line 56 of file UserInputBox.java.
Member Data Documentation
BasicParser gui.UserInputBox.myParser private
Definition at line 24 of file UserInputBox.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/gui/UserInputBox.java