slogo_team16: Tree.SingleNode Class Reference
Tree.SingleNode Class Reference
Public Member Functions
SingleNode (String s, Node c, CommandFactory cf)
double getValue ()
String toString ()
int hasChild ()
Private Attributes
final int numChild = 1
String command
Node child
CommandFactory myFactory
Detailed Description
Represents a single node with one child/commands with only one parameter
Author
Yongjiao Yu
Definition at line 13 of file SingleNode.java.
Constructor & Destructor Documentation
Tree.SingleNode.SingleNode (String s, Node c, CommandFactory cf)
Definition at line 19 of file SingleNode.java.
Member Function Documentation
double Tree.SingleNode.getValue ()
Implements Tree.Node.
Definition at line 26 of file SingleNode.java.
References commands.viewCommands.turtleCommands.Executable.execute(), Tree.Node.getValue(), and application.CommandFactory.makeBasicCommands().
int Tree.SingleNode.hasChild ()
Implements Tree.Node.
Definition at line 42 of file SingleNode.java.
References Tree.SingleNode.numChild.
String Tree.SingleNode.toString ()
Definition at line 35 of file SingleNode.java.
Member Data Documentation
Node Tree.SingleNode.child private
Definition at line 16 of file SingleNode.java.
String Tree.SingleNode.command private
Definition at line 15 of file SingleNode.java.
CommandFactory Tree.SingleNode.myFactory private
Definition at line 17 of file SingleNode.java.
final int Tree.SingleNode.numChild = 1 private
Definition at line 14 of file SingleNode.java.
Referenced by Tree.SingleNode.hasChild().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/Tree/SingleNode.java