slogo_team16: application.Pen Class Reference
application.Pen Class Reference
Classes
enum PENSTYLE
Public Member Functions
Pen ()
void setStatus (int newStatus)
int getStatus ()
String getStatusString ()
void setColor (Color newColor)
void setColor (int indexOfColor)
Color getColor ()
void setWeight (double newWeight)
double getWeight ()
void setStyle (PENSTYLE newStyle)
PENSTYLE getStyle ()
void setPaletteColor (int paletteIndex, int redIndex, int greenIndex, int blueIndex)
Color getColorFromPalette (int index)
int getCurrentColorIndexFromPalette ()
Package Attributes
int myPaletteColorLocation
Private Attributes
int myStatus
Color myColor
double myThickness
PENSTYLE myStyle
Map< Integer, Color > myPaletteOptions
Detailed Description
Author
Anika
Definition at line 13 of file Pen.java.
Constructor & Destructor Documentation
application.Pen.Pen ()
Constructor of pen class
initializes status to 1
initializes color to black
initializes original thickness to 1
initializes line-drawing style to solid line
Parameters
status
Definition at line 33 of file Pen.java.
References application.Pen.PENSTYLE.SOLID.
Member Function Documentation
Color application.Pen.getColor ()
Returns
color of pen
Definition at line 98 of file Pen.java.
References application.Pen.myColor.
Referenced by application.PenHandler.getPenColor().
Color application.Pen.getColorFromPalette (int index)
Parameters
index of desired color
Returns
Color from Palette Map
Definition at line 162 of file Pen.java.
References application.Pen.myColor.
Referenced by application.Pen.setColor(), and application.PenHandler.setPenColor().
int application.Pen.getCurrentColorIndexFromPalette ()
called when PENCOLOR command is executed (Sprint 3)
Returns
int index of current pen color
Definition at line 172 of file Pen.java.
References application.Pen.myPaletteColorLocation.
Referenced by application.PenHandler.getPenColorIndex().
int application.Pen.getStatus ()
Returns
current status of pen: 1 if DOWN; 0 if UP
Definition at line 58 of file Pen.java.
References application.Pen.myStatus.
Referenced by application.PenHandler.getPenStatus().
String application.Pen.getStatusString ()
Used for displaying pen status to user in a readable form Single if statement used since condition for mapping 1 to DOWN and 0 to UP is only referred to once in the code
Returns
current status of pen in the form of a string
Definition at line 69 of file Pen.java.
PENSTYLE application.Pen.getStyle ()
Returns
current style of pen
Definition at line 137 of file Pen.java.
References application.Pen.myStyle.
double application.Pen.getWeight ()
Returns
thickness of pen
Definition at line 116 of file Pen.java.
References application.Pen.myThickness.
Referenced by application.PenHandler.getPenWeight().
void application.Pen.setColor (Color newColor)
Sets color of pen to inputted pen color
Parameters
newColor
Definition at line 79 of file Pen.java.
Referenced by application.PenHandler.setPenColor().
void application.Pen.setColor (int indexOfColor)
sets color of pen to returned color from index key of Palette map
Parameters
indexOfColor
Definition at line 89 of file Pen.java.
References application.Pen.getColorFromPalette().
void application.Pen.setPaletteColor (int paletteIndex, int redIndex, int greenIndex, int blueIndex)
Creates new Color with given index from RGB input values Adds color and index to Map
Parameters
paletteIndex
redIndex
greenIndex
blueIndex
Definition at line 151 of file Pen.java.
Referenced by application.PenHandler.setPaletteColor().
void application.Pen.setStatus (int newStatus)
sets status of pen based on input parameter if status == 1, PENDOWN if status == 0, PENUP
Parameters
newStatus of pen
Definition at line 50 of file Pen.java.
Referenced by application.PenHandler.setPenStatus().
void application.Pen.setStyle (PENSTYLE newStyle)
Sets style of pen's line drawing based on input parameter Choices:
solid
dotted
dashed
Parameters
newStyle
Definition at line 129 of file Pen.java.
void application.Pen.setWeight (double newWeight)
Sets thickness of pen based on inputted value Higher values correspond to thicker lines
Parameters
newWeight
Definition at line 108 of file Pen.java.
Referenced by application.PenHandler.setPenWeight().
Member Data Documentation
Color application.Pen.myColor private
Definition at line 16 of file Pen.java.
Referenced by application.Pen.getColor(), and application.Pen.getColorFromPalette().
int application.Pen.myPaletteColorLocation package
Definition at line 15 of file Pen.java.
Referenced by application.Pen.getCurrentColorIndexFromPalette().
Map<Integer, Color> application.Pen.myPaletteOptions private
Definition at line 19 of file Pen.java.
int application.Pen.myStatus private
Definition at line 15 of file Pen.java.
Referenced by application.Pen.getStatus().
PENSTYLE application.Pen.myStyle private
Definition at line 18 of file Pen.java.
Referenced by application.Pen.getStyle().
double application.Pen.myThickness private
Definition at line 17 of file Pen.java.
Referenced by application.Pen.getWeight().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/application/Pen.java