slogo_team16: commands.viewCommands.turtleCommands.RunUD Class Reference
commands.viewCommands.turtleCommands.RunUD Class Reference
Public Member Functions
RunUD (String n, ArrayList< Object > vals)
double execute ()
Public Member Functions inherited from commands.viewCommands.turtleCommands.TurtleCommands
TurtleCommands ()
TurtleCommands (ViewHandler v)
TurtleCommands (ArrayList< Object > p, ViewHandler v)
void setViewHandler (ViewHandler newHandler)
double execute ()
Public Member Functions inherited from commands.CommandCenter
CommandCenter ()
void restore (ArrayList< Integer > l, String s)
Static Public Member Functions
static void main (String[] arg)
Private Attributes
String name
ArrayList< Object > values
Additional Inherited Members
Protected Member Functions inherited from commands.viewCommands.turtleCommands.TurtleCommands
ViewHandler getHandler ()
void setParams (ArrayList< Object > newParams)
ArrayList< Object > getParams ()
Protected Member Functions inherited from commands.CommandCenter
void setParams (ArrayList< Object > newParams)
ArrayList< Object > getParams ()
Detailed Description
Definition at line 10 of file RunUD.java.
Constructor & Destructor Documentation
commands.viewCommands.turtleCommands.RunUD.RunUD (String n, ArrayList< Object > vals)
Definition at line 15 of file RunUD.java.
Referenced by commands.viewCommands.turtleCommands.RunUD.main().
Member Function Documentation
double commands.viewCommands.turtleCommands.RunUD.execute ()
Author
Anika, Richard
    - create map of params : vals - for each command --> replace
    if needed
Implements commands.viewCommands.turtleCommands.Executable.
Definition at line 20 of file RunUD.java.
References commands.UserDefined.getCommands(), commands.UserMadeUtilities.getFromCommands(), commands.UserDefined.getParameters(), commands.CommandCenter.getParams(), and commands.UserDefined.makeInstanceOfSelf().
static void commands.viewCommands.turtleCommands.RunUD.main (String[] arg) static
Definition at line 73 of file RunUD.java.
References commands.viewCommands.turtleCommands.RunUD.RunUD().
Member Data Documentation
String commands.viewCommands.turtleCommands.RunUD.name private
Definition at line 12 of file RunUD.java.
ArrayList<Object> commands.viewCommands.turtleCommands.RunUD.values private
Definition at line 13 of file RunUD.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/commands/viewCommands/turtleCommands/RunUD.java