slogo_team16: configuration.ForParser Class Reference
configuration.ForParser Class Reference
Public Member Functions
ForParser (CommandFactory cf) throws IOException
double parse (String s) throws ParserError
Private Member Functions
double parse (Queue< String > tokens) throws ParserError
double parseCommands (Queue< String > qu, int start, int end, int inc) throws ParserError
int fetchNumericExpr (Queue< String > qu) throws ParserError
double parseFor (int start, int end, int inc, Queue< String > qu) throws ParserError
Private Attributes
String localVar
CommandFactory myFactory
Additional Inherited Members
Protected Member Functions inherited from configuration.Parser
Parser () throws IOException
void setCommandFactory (CommandFactory cf)
abstract double parse (String s) throws ParserError, IOException
void initialize () throws IOException
void setLanguage (String path)
void initializeSyntax ()
void initializeSets () throws IOException
Node buildTree (Queue< String > tokens) throws ParserError
Node buildTree (Queue< String > tokens, String localVar, int iterator) throws ParserError
boolean isListEnd (String s)
boolean isListStart (String s)
boolean isVariable (String s)
boolean isConstant (String s)
boolean isCommand (String s)
void skip (Queue< String > qu)
boolean isEnd (Queue< String > qu)
List< Entry< String, Pattern > > getPatterns ()
Package Attributes inherited from configuration.Parser
String constant
String variable
String command
String liststart
String listend
String groupstart
String groupend
Detailed Description
subclass for For command parsing
Author
Yongjiao Yu
Definition at line 19 of file ForParser.java.
Constructor & Destructor Documentation
configuration.ForParser.ForParser (CommandFactory cf) throws IOException
Definition at line 23 of file ForParser.java.
Member Function Documentation
int configuration.ForParser.fetchNumericExpr (Queue< String > qu) throws ParserError private
Definition at line 64 of file ForParser.java.
References configuration.Parser.buildTree(), and Tree.Node.getValue().
Referenced by configuration.ForParser.parse().
double configuration.ForParser.parse (String s) throws ParserError
Definition at line 28 of file ForParser.java.
References configuration.Parser.skip(), and configuration.Util.toCommandQueue().
double configuration.ForParser.parse (Queue< String > tokens) throws ParserError private
Definition at line 34 of file ForParser.java.
References configuration.ForParser.fetchNumericExpr(), configuration.Parser.isEnd(), configuration.Parser.isListEnd(), configuration.Parser.isListStart(), configuration.Parser.isVariable(), configuration.ForParser.parseCommands(), and configuration.Parser.skip().
double configuration.ForParser.parseCommands (Queue< String > qu, int start, int end, int inc) throws ParserError private
Definition at line 54 of file ForParser.java.
References configuration.Parser.isEnd(), configuration.Parser.isListEnd(), configuration.Parser.isListStart(), configuration.ForParser.parseFor(), and configuration.Parser.skip().
Referenced by configuration.ForParser.parse().
double configuration.ForParser.parseFor (int start, int end, int inc, Queue< String > qu) throws ParserError private
Definition at line 68 of file ForParser.java.
References configuration.Parser.buildTree(), Tree.Node.getValue(), configuration.Parser.isEnd(), configuration.Parser.isListEnd(), and configuration.Parser.skip().
Referenced by configuration.ForParser.parseCommands().
Member Data Documentation
String configuration.ForParser.localVar private
Definition at line 20 of file ForParser.java.
CommandFactory configuration.ForParser.myFactory private
Definition at line 21 of file ForParser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/configuration/ForParser.java