slogo_team16: application.Main Class Reference
application.Main Class Reference
Public Member Functions
void start (Stage stage)
Static Public Member Functions
static void main (String[] args)
Private Attributes
ArrayList< GUI > myGUIs = new ArrayList<>()
Static Private Attributes
static final int NUM_WORKSPACES = 3
Detailed Description
Definition at line 28 of file Main.java.
Member Function Documentation
static void application.Main.main (String[] args) static
Definition at line 150 of file Main.java.
void application.Main.start (Stage stage)
Definition at line 35 of file Main.java.
References gui.GUI.getBackgroundView(), gui.GUI.getLineView(), gui.GUI.getTurtleView(), gui.GUI.initialize(), application.Main.NUM_WORKSPACES, gui.GUI.setParser(), application.CommandFactory.setPenHandler(), application.CommandFactory.setViewHandler(), and commands.viewCommands.turtleCommands.TurtleCommands.setViewHandler().
Member Data Documentation
ArrayList<GUI> application.Main.myGUIs = new ArrayList<>() private
Definition at line 32 of file Main.java.
final int application.Main.NUM_WORKSPACES = 3 static private
Definition at line 30 of file Main.java.
Referenced by application.Main.start().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/application/Main.java