slogo_team16: Tree.Node Interface Reference
Tree.Node Interface Reference
Public Member Functions
abstract double getValue ()
abstract int hasChild ()
Detailed Description
superclass of all Nodes Represents a node of any type in an expression tree.
Author
Yongjiao Yu
Definition at line 8 of file Node.java.
Member Function Documentation
abstract double Tree.Node.getValue () abstract
Implemented in Tree.BinNode, Tree.SingleNode, and Tree.ConstNode.
Referenced by configuration.IfelseParser.evaluateBoolExpr(), configuration.RepeatParser.fetchNumericExpr(), configuration.ForParser.fetchNumericExpr(), configuration.DotimesParser.fetchNumericExpr(), Tree.SingleNode.getValue(), Tree.BinNode.getValue(), configuration.SetParser.parse(), configuration.BasicParser.parse(), configuration.ForParser.parseFor(), and configuration.DotimesParser.parseFor().
abstract int Tree.Node.hasChild () abstract
Implemented in Tree.BinNode, Tree.SingleNode, and Tree.ConstNode.
Referenced by configuration.BasicParser.parse().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/Tree/Node.java