slogo_team16: configuration.DotimesParser Class Reference
configuration.DotimesParser Class Reference
Public Member Functions
DotimesParser (CommandFactory cf) throws IOException
double parse (String s) throws ParserError
Static Public Member Functions
static void main (String[] args) throws IOException, ParserError
Protected Member Functions
double parseFor (int start, int end, int inc, Queue< String > qu) throws ParserError
Protected Member Functions inherited from configuration.Parser
Parser () throws IOException
void setCommandFactory (CommandFactory cf)
abstract double parse (String s) throws ParserError, IOException
void initialize () throws IOException
void setLanguage (String path)
void initializeSyntax ()
void initializeSets () throws IOException
Node buildTree (Queue< String > tokens) throws ParserError
Node buildTree (Queue< String > tokens, String localVar, int iterator) throws ParserError
boolean isListEnd (String s)
boolean isListStart (String s)
boolean isVariable (String s)
boolean isConstant (String s)
boolean isCommand (String s)
void skip (Queue< String > qu)
boolean isEnd (Queue< String > qu)
List< Entry< String, Pattern > > getPatterns ()
Private Member Functions
double parse (Queue< String > tokens) throws ParserError
double parseCommands (Queue< String > qu, int limit) throws ParserError
int parseDotimesIterator (Queue< String > qu) throws ParserError
int fetchNumericExpr (Queue< String > qu) throws ParserError
Private Attributes
String localVar = ""
CommandFactory myFactory
Additional Inherited Members
Package Attributes inherited from configuration.Parser
String constant
String variable
String command
String liststart
String listend
String groupstart
String groupend
Detailed Description
subclass for Dotimes command parsing
Author
Yongjiao Yu
Definition at line 19 of file DotimesParser.java.
Constructor & Destructor Documentation
configuration.DotimesParser.DotimesParser (CommandFactory cf) throws IOException
Definition at line 23 of file DotimesParser.java.
Member Function Documentation
int configuration.DotimesParser.fetchNumericExpr (Queue< String > qu) throws ParserError private
Definition at line 66 of file DotimesParser.java.
References configuration.Parser.buildTree(), and Tree.Node.getValue().
Referenced by configuration.DotimesParser.parseDotimesIterator().
static void configuration.DotimesParser.main (String[] args) throws IOException, ParserError static
Definition at line 95 of file DotimesParser.java.
double configuration.DotimesParser.parse (String s) throws ParserError
Definition at line 28 of file DotimesParser.java.
References configuration.Parser.skip(), and configuration.Util.toCommandQueue().
double configuration.DotimesParser.parse (Queue< String > tokens) throws ParserError private
Definition at line 33 of file DotimesParser.java.
References configuration.Parser.isEnd(), configuration.DotimesParser.parseCommands(), and configuration.DotimesParser.parseDotimesIterator().
double configuration.DotimesParser.parseCommands (Queue< String > qu, int limit) throws ParserError private
Definition at line 41 of file DotimesParser.java.
References configuration.Parser.isEnd(), configuration.Parser.isListEnd(), configuration.Parser.isListStart(), configuration.DotimesParser.parseFor(), and configuration.Parser.skip().
Referenced by configuration.DotimesParser.parse().
int configuration.DotimesParser.parseDotimesIterator (Queue< String > qu) throws ParserError private
Definition at line 52 of file DotimesParser.java.
References configuration.DotimesParser.fetchNumericExpr(), configuration.Parser.isListEnd(), configuration.Parser.isListStart(), configuration.Parser.isVariable(), and configuration.Parser.skip().
Referenced by configuration.DotimesParser.parse().
double configuration.DotimesParser.parseFor (int start, int end, int inc, Queue< String > qu) throws ParserError protected
Parses for loop and handles local variable
Parameters
qu
Returns
Exceptions
ParserError
Definition at line 80 of file DotimesParser.java.
References configuration.Parser.buildTree(), Tree.Node.getValue(), configuration.Parser.isEnd(), configuration.Parser.isListEnd(), and configuration.Parser.skip().
Referenced by configuration.DotimesParser.parseCommands().
Member Data Documentation
String configuration.DotimesParser.localVar = "" private
Definition at line 20 of file DotimesParser.java.
CommandFactory configuration.DotimesParser.myFactory private
Definition at line 21 of file DotimesParser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/configuration/DotimesParser.java