slogo_team16: gui.LineView Class Reference
gui.LineView Class Reference
Public Member Functions
LineView (int x, int y)
void drawLine (Point2D orig, Point2D dest)
void clearScreen ()
void setColor (Color c)
void setThickness (double lw)
void setParamsOfPen (Color color, double thickness)
Public Member Functions inherited from gui.View
View (int x, int y)
Point2D getNewPoint ()
void setNewPoint (Point2D dest)
double getXOffset ()
double getYOffset ()
Package Attributes
double YOFFSET
Point2D newDest
Private Member Functions
Point2D findBoundaryPoint (Point2D orig, Point2D dest)
Point2D findCorner (double x, double y, double mCorner, double slope, Point2D dest)
Point2D findXEdge (double x, double slope, Point2D dest)
Point2D findYEdge (double y, double slope, Point2D dest)
Private Attributes
GraphicsContext linesGC
double XOFFSET
Point2D newStart
Static Private Attributes
static final Color DEFAULT_PEN_COLOR = Color.BLACK
Additional Inherited Members
Static Package Attributes inherited from gui.View
static double YOFFSET
Detailed Description
Creates the line drawing layer
Author
Andrew
Definition at line 12 of file LineView.java.
Constructor & Destructor Documentation
gui.LineView.LineView (int x, int y)
Definition at line 19 of file LineView.java.
References gui.View.getNewPoint().
Member Function Documentation
void gui.LineView.clearScreen ()
Clears all lines
Definition at line 146 of file LineView.java.
Referenced by application.ViewHandler2.clearScreen(), and application.ViewHandler.clearScreen().
void gui.LineView.drawLine (Point2D orig, Point2D dest)
Draws a line from one point to another Accounts for destination point being out of bounds of canvas
Parameters
orig original coordinates of the turtle (turtle coordinate system)
dest destination coordinates of the turtle (turtle coordinate system)
c color of line drawn
Definition at line 36 of file LineView.java.
References gui.LineView.findBoundaryPoint(), gui.View.setNewPoint(), gui.LineView.XOFFSET, and gui.LineView.YOFFSET.
Referenced by application.ViewHandler2.moveTurtleImageAndDraw(), and application.ViewHandler.moveTurtleImageAndDraw().
Point2D gui.LineView.findBoundaryPoint (Point2D orig, Point2D dest) private
This helper method returns a point where the turtle crosses a boundary. If the turtle doesn't cross a boundary, the method returns null.
Parameters
orig original coordinates of the turtle (turtle coordinate system)
dest destination coordinates of the turtle (turtle coordinate system)
Returns
a point where the turtle crosses a boundary
Definition at line 61 of file LineView.java.
References gui.LineView.findCorner(), gui.LineView.findXEdge(), gui.LineView.findYEdge(), gui.LineView.XOFFSET, and gui.LineView.YOFFSET.
Referenced by gui.LineView.drawLine().
Point2D gui.LineView.findCorner (double x, double y, double mCorner, double slope, Point2D dest) private
Parameters
x
y
mCorner
slope
dest
Returns
Definition at line 103 of file LineView.java.
References gui.LineView.findXEdge(), and gui.LineView.findYEdge().
Referenced by gui.LineView.findBoundaryPoint().
Point2D gui.LineView.findXEdge (double x, double slope, Point2D dest) private
Parameters
x
slope
dest
Returns
Definition at line 119 of file LineView.java.
References gui.View.setNewPoint().
Referenced by gui.LineView.findBoundaryPoint(), and gui.LineView.findCorner().
Point2D gui.LineView.findYEdge (double y, double slope, Point2D dest) private
Parameters
y
slope
dest
Returns
Definition at line 134 of file LineView.java.
References gui.View.setNewPoint().
Referenced by gui.LineView.findBoundaryPoint(), and gui.LineView.findCorner().
void gui.LineView.setColor (Color c)
Sets color of line drawn
Parameters
c
Definition at line 154 of file LineView.java.
Referenced by gui.GUI.createColorPickerButtons().
void gui.LineView.setParamsOfPen (Color color, double thickness)
Definition at line 163 of file LineView.java.
void gui.LineView.setThickness (double lw)
Definition at line 159 of file LineView.java.
Referenced by application.PenHandler.setThicknessParameter().
Member Data Documentation
final Color gui.LineView.DEFAULT_PEN_COLOR = Color.BLACK static private
Definition at line 16 of file LineView.java.
GraphicsContext gui.LineView.linesGC private
Definition at line 14 of file LineView.java.
Point2D gui.LineView.newDest package
Definition at line 17 of file LineView.java.
Point2D gui.LineView.newStart private
Definition at line 17 of file LineView.java.
double gui.LineView.XOFFSET private
Definition at line 15 of file LineView.java.
Referenced by gui.LineView.drawLine(), and gui.LineView.findBoundaryPoint().
double gui.LineView.YOFFSET package
Definition at line 15 of file LineView.java.
Referenced by gui.LineView.drawLine(), and gui.LineView.findBoundaryPoint().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team16/repository/src/gui/LineView.java